User/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='User'

urlpatterns = [
    path('',views.index,name='index'),
    path('user_login/',views.user_login,name='user_login'),
    path('register/',views.register,name='register')
]

User_From_Scratch/urls.py
from django.contrib import admin
from django.urls import path,include
from User import views

urlpatterns = [
    path('',views.index,name='index'),
    path('User/',include('User.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('admin/', admin.site.urls),
]

User/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    username = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics')


    def __str__(self):

        return str(self.username)

User/forms.py
from django import forms
from User.models import UserProfileInfo
from django.contrib.auth.models import User

class UserProfileInfoForm(forms.ModelForm):
    portfolio_site = forms.URLField(required=False)
    profile_pic = forms.ImageField(required=False)

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

User/views.py
from django.shortcuts import render
from .forms import UserProfileInfoForm,UserForm
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse



def index(request):

    return render(request,'index.html')


# Create your views here.
def user_login(request):

    Logged_In = False
    Bad_User = False

    if request.method == "POST":


        username = request.POST['username']
        password = request.POST['password']
        print(request)

        user = authenticate(request,username=username,password=password)

        if user is not None:



            if user.is_authenticated:

                Logged_In=True

                login(request,user)



        else:
            Bad_User = True
            print("Bad Login:\t {}\t:\t{}".format(username,password))





    return render(request,'login.html',{'Logged_In':Logged_In,'Bad_User':Bad_User})





def register(request):

    registered = False

    if request.method == "POST":

        userprofile_form = UserProfileInfoForm(data=request.POST)
        user_form = UserForm(data=request.POST)

        if userprofile_form.is_valid() and user_form.is_valid():

            print(user_form.data)
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile_data =userprofile_form.save(commit=False)
            profile_data.username = user
            print(userprofile_form.data)
            print(userprofile_form.data['username'])

            if 'profile_pic' in request.FILES:

                profile_data.picture = request.FILES('profile_pic')



            profile_data.save()

            registered=True

            return render(request, 'registration.html', {'user_form': user_form, 'profile_form': userprofile_form, 'registered': registered})

        else:
            print(user_form.errors)
            print(userprofile_form.errors)

    else:



        user_form = UserForm()
        profile_form = UserProfileInfoForm()


        return render(request,'registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>{% block Title_Block %}{% endblock %}</title>
</head>
<body>

    <nav class = "navbar nav-default navbar-static-top navbar-inverse">

         <div class="container">


          <ul class="nav navbar-nav">

            <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'User:register' %}">Register</a></li>
          </ul>

             <ul class = "nav navbar-nav navbar-right">

              {% if user.is_authenticated %}

              <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>



             {% else %}

              <li><a class="navbar-link" href="{% url 'User:user_login' %}">Login</a></li>



             {% endif %}

          </ul>


         </div>

    </nav>
    <div class="container" style="width:70%">
        {% block Body_Block %}
        {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block Title_Block %}
Home
{% endblock %}


{% block Body_Block %}
<div class="jumbotron" style="text-align:center">

    <h1>Welcome!</h1>
    <h3>To login please click on the login link!</h3>
    <h3>To register please click on the register link!</h3>

</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block Title_Block %}
Login
{% endblock %}


{% block Body_Block %}

    {% if Logged_In and not Bad_User %}


        <div class="jumbotron">

            <h1>You are now Logged in!</h1>

        </div>


    {% elif not Bad_User %}


        <div class = "jumbotron" style="text-align:center">

            <h3>Please Login:</h3><br/><br/>

            <form actions="{% url 'User:user_login' %}" method="post">

                {% csrf_token %}

                <label for="username">Username:</label>
                <input type="text" name="username" value="" placeholder="Enter Username Here"><br/><br/>

                <label for="password">Passowrd:</label>
                <input type="password" name="password" placeholder="Enter Password Here"><br/><br/>

                <input type="submit" value="Login">




            </form>

        </div>

    {% elif Bad_User %}

        <div class = "jumbotron">

            <form actions="{% url 'User:user_login' %}" method="post">

                {% csrf_token %}

                <p>Incorrect Username or Password!</p>

                <label for="username">Username:</label>
                <input type="text" name="username" value="" placeholder="Enter Username Here"><br/><br/>

                <label for="password">Passowrd:</label>
                <input type="password" name="password" placeholder="Enter Password Here"><br/><br/>

                <input type="submit" value="Login">




            </form>

        </div>





    {% endif %}



{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block Title_Block %}
Registration
{% endblock %}


{% block Body_Block %}

    <div class="jumbotron">

        {% if  registered %}

        <h1>Thank you for registering!</h1>

        {% else %}

            <h1>Register Here:</h1>
            <h3>Fill out the form:</h3>
            <br/>
            <br/>
            <br/>

            <form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <br>
                <br>
                <input type="submit" class="btn btn-primary" name="" value="Register">

            </form>

        {% endif %}
    </div>


{% endblock %}